"""
SensorCalibrator Sensors Module

传感器模块，提供安装模式、滤波、多级报警和辅助传感器配置。
"""

from .install_mode import (
    InstallMode,
    build_isg_command,
    validate_install_mode,
    get_mode_description,
    get_mode_category,
    get_category_display_name,
    get_modes_by_category,
    get_all_modes_for_ui,
    get_modes_grouped_by_category,
    suggest_mode_by_installation,
    build_default_mode_command,
    build_ground_mode_command,
    build_side_mode_command,
    build_top_mode_command,
    INSTALL_MODE_DESCRIPTIONS,
    INSTALL_MODE_CATEGORIES,
    CATEGORY_NAMES,
)

from .filter import (
    build_kfqr_command,
    build_ss17_toggle_filter,
    validate_process_noise,
    validate_measurement_noise,
    build_default_filter_command,
    build_filter_on_command,
    build_filter_off_command,
    FILTER_PRESETS,
    get_filter_preset,
    get_all_filter_presets,
    MIN_PROCESS_NOISE,
    MAX_PROCESS_NOISE,
    DEFAULT_PROCESS_NOISE,
    MIN_MEASUREMENT_NOISE,
    MAX_MEASUREMENT_NOISE,
    DEFAULT_MEASUREMENT_NOISE,
)

from .level_config import (
    build_grolevel_command,
    build_acclevel_command,
    validate_level_thresholds,
    build_default_grolevel_command,
    build_default_acclevel_command,
    GROLEVEL_PRESETS,
    ACCLEVEL_PRESETS,
    get_grolevel_preset,
    get_acclevel_preset,
    get_all_grolevel_presets,
    get_all_acclevel_presets,
    LEVEL_DESCRIPTIONS,
    get_level_description,
    NUM_ALARM_LEVELS,
    GROLEVEL_MIN,
    GROLEVEL_MAX,
    ACCLEVEL_MIN,
    ACCLEVEL_MAX,
)

from .auxiliary import (
    build_vks_command,
    build_tme_command,
    build_magof_command,
    validate_voltage_scale,
    validate_temperature_offset,
    validate_magnetic_offset,
    build_default_vks_command,
    build_default_tme_command,
    build_default_magof_command,
    get_auxiliary_sensor_info,
    VKS_MIN,
    VKS_MAX,
    VKS_DEFAULT,
    TME_MIN,
    TME_MAX,
    TME_DEFAULT,
    MAGOF_MIN,
    MAGOF_MAX,
    MAGOF_DEFAULT,
)

__all__ = [
    # Install Mode
    'InstallMode',
    'build_isg_command',
    'validate_install_mode',
    'get_mode_description',
    'get_mode_category',
    'get_category_display_name',
    'get_modes_by_category',
    'get_all_modes_for_ui',
    'get_modes_grouped_by_category',
    'suggest_mode_by_installation',
    'build_default_mode_command',
    'build_ground_mode_command',
    'build_side_mode_command',
    'build_top_mode_command',
    'INSTALL_MODE_DESCRIPTIONS',
    'INSTALL_MODE_CATEGORIES',
    'CATEGORY_NAMES',
    # Filter
    'build_kfqr_command',
    'build_ss17_toggle_filter',
    'validate_process_noise',
    'validate_measurement_noise',
    'build_default_filter_command',
    'build_filter_on_command',
    'build_filter_off_command',
    'FILTER_PRESETS',
    'get_filter_preset',
    'get_all_filter_presets',
    'MIN_PROCESS_NOISE',
    'MAX_PROCESS_NOISE',
    'DEFAULT_PROCESS_NOISE',
    'MIN_MEASUREMENT_NOISE',
    'MAX_MEASUREMENT_NOISE',
    'DEFAULT_MEASUREMENT_NOISE',
    # Level Config
    'build_grolevel_command',
    'build_acclevel_command',
    'validate_level_thresholds',
    'build_default_grolevel_command',
    'build_default_acclevel_command',
    'GROLEVEL_PRESETS',
    'ACCLEVEL_PRESETS',
    'get_grolevel_preset',
    'get_acclevel_preset',
    'get_all_grolevel_presets',
    'get_all_acclevel_presets',
    'LEVEL_DESCRIPTIONS',
    'get_level_description',
    'NUM_ALARM_LEVELS',
    'GROLEVEL_MIN',
    'GROLEVEL_MAX',
    'ACCLEVEL_MIN',
    'ACCLEVEL_MAX',
    # Auxiliary Sensors
    'build_vks_command',
    'build_tme_command',
    'build_magof_command',
    'validate_voltage_scale',
    'validate_temperature_offset',
    'validate_magnetic_offset',
    'build_default_vks_command',
    'build_default_tme_command',
    'build_default_magof_command',
    'get_auxiliary_sensor_info',
    'VKS_MIN',
    'VKS_MAX',
    'VKS_DEFAULT',
    'TME_MIN',
    'TME_MAX',
    'TME_DEFAULT',
    'MAGOF_MIN',
    'MAGOF_MAX',
    'MAGOF_DEFAULT',
]
